---
- name: Ansible Homelab
  hosts: localhost
  vars_files: ["defaults/settings.yml.default", "settings.yml"]
  roles:
    # Applications roles
    - {role: actualbudget, tags: ["extra", "actualbudget"]}
    - {role: homebox, tags: ["extra", "homebox"]}
    - {role: yamtrack, tags: ["extra", "yamtrack"]}
