---
- name: Start Actual Budget
  block:
    - name: Check for Actual Budget Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: actualbudget

    - name: Create Actual Budget Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0775
        recurse: yes
      with_items:
        - "{{ actualbudget.folder }}/data"

    - name: Create Actual Budget Docker Container
      community.docker.docker_container:
        name: actualbudget
        image: "actualbudget/actual-server:{{ actualbudget.tag }}"
        restart_policy: unless-stopped
        volumes:
          - "{{ actualbudget.folder }}/data"
        healthcheck:
          test: ['CMD-SHELL', 'node src/scripts/health-check.js']
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 20s
        labels:
          # Traefik
          traefik.enable: "true"
          traefik.docker.network: "web"
          traefik.http.routers.actualbudget.rule: "Host(`{{ actualbudget.subdomain }}.{{ domain }}`)"
          traefik.http.routers.actualbudget.entrypoints: "websecure"
          traefik.http.services.actualbudget.loadbalancer.server.port: "5006"
